### PR TITLE
implement initial version

### PR DESCRIPTION
**Pull request by RobTillaart**
implementation of functionality - discussed with pt by mail)

### CODE REVIEW

**Comment by ladyada** [comment]
hiya! ok first thing you have to do is run `clang-format` on the *cpp and *h files, you can install clangformat on your computer pretty easily. we do this because many IDE's auto-clang and we had so many PR's that had really different formatting it made merging hard.

here's a guide on clang-format: https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

once run, re-commit and it should pass that stage - let me know if you're having difficulties still

**Comment by RobTillaart** [comment]
@ladyada 
Thanks, build restarted.

**Comment by RobTillaart** [comment]
@ladyada 
**fatal: Remote branch gh-pages not found in upstream origin**

something missing in your branch?

**Comment by RobTillaart** [comment]
In a previous run  the test-examples compiled.

I updated the yml workflow from the BusIO repo as that one is more recent, 
and apparently the order of commands changed.

I will change it back as imho testing the code should be done first.

**Comment by ladyada** [comment]
ok merged for now and added gh-pages branch to autogenerate the doxygen pages!

**Pull request merged**
